### ISSUE TITLE
Can't paste from clipboard

### ISSUE THREAD

**Issue by sudo-nice** [boothj5/profanity#730] opened 2016-02-04 12:57 UTC
Here, on Linux, I can't find a way to paste text from the clipboard (what we can see with `xsel -ob`). Normaly I can paste from clipboard in my urxvt with M-v hotkey, but instead of pasting the content, profanity prints the hotkey itself. Now I have to paste from the primary selection (with Shift-Ins or middle mouse button), but it's awkward. Is there any solution?

**Comment by boothj5** [comment] 2016-02-04 21:23
Closing as a duplicate of #156

This issue has been around for a long time, but other features/bugs have always taken priority.  It's been raised enough times that I'll try to look into it, probably not for the next release, but soon after.

**Closed by boothj5** 2016-02-04 21:23 UTC
