### ISSUE TITLE
OTR, profanity doesn't decrypt 1st message from Android Conversations

### ISSUE THREAD

**Issue by quite** [boothj5/profanity#558] opened 2015-06-14 09:53 UTC
OTR interop with Android app Conversations is not 100%. I have profanity running with jid1, and jid2 in Conversations. I start a conversation with jid1, verify that OTR is chosen, and type a first message to jid1, and proceed to send it.

What I now get in profanity is the encrypted message: TIME jid2 ?OTR:AAIDAAA […] =.

I type another message, and profanity manages to decrypt and show it.

**Comment by quite** [comment] 2015-06-26 11:09
Currently, upon the first message from jid2-conversations to jid1-profanity, OTR is started and profanity opens up a new window. But the actual message is not displayed. The 2nd message from jid2 gets through OTR, and is decrypted.

**Comment by devhell** [comment] 2015-08-01 09:35
I can confirm that the first message from a Conversations using OTR results in ?OTR:... being displayed.

**Comment by devhell** [comment] 2015-09-06 12:23
@quite Do you still have this problem with the latest `Conversations` version?

**Comment by quite** [comment] 2015-09-07 10:08
Yes.

**Comment by devhell** [comment] 2015-09-07 18:28
@quite Do you, by any chance, know what server software is being used? The XMPP server I'm using recently switched from `ejabberd` to `mongooseim` and this problem went away. I have no idea how this is related, but that's the only other change that I noticed.

**Comment by quite** [comment] 2015-09-07 18:46
Yes I do, it's Prosody. I'm not using Conversations much these days, and currently we're having some other otr problems over this server, between profanity and https://github.com/agl/xmpp-client. Perhaps it's not the server, but trying something else is an idea...

**Comment by boothj5** [comment] 2015-09-07 19:23
In principle, the server should have no impact since it knows nothing about OTR.  However I guess we can't rule it out until we've found the cause.

Just to confirm, your scenario is:
1) Other client: Start OTR session
2) Other client: OTR session confirmed
3) Other client: Send message
4) **Profanity: Doesn't decrypt**
5) Other client: Send another message
6) Profanity: Decrypts successfully

Does Profanity also confirm that an OTR session has been started before step 3:
* If you have a chat window open already with the contact when they start the OTR session, Profanity should display something like `OTR session started` in that window.
* If you don't have a window open when the other client starts the session, you should see `contact@server.org started an OTR session (N).` in the console window, where N is the new window number, going to that window will show `OTR session started` as above.

Testing Profanity <-> Psi+ works ok in the above scenario, and when the OTR session is started with Profanity.

**Comment by quite** [comment] 2015-09-07 19:40
Nice walkthrough! I tried it again now with Conversations, and that is what happens, almost. The only detail is that there is not way in conversations to "start an OTR session". You type a message in OTR mode, and send it. What I see in Profanity is "foo started an OTR session" and directly "<< incoming from foo". And there I get the unreadable message, in ciphertext. Next message, and it's decrypted.

**Comment by boothj5** [comment] 2015-09-07 20:07
If Conversations doesn't support manually starting OTR sessions, I assume it must be using an "opportunistic" OTR policy.

If this is the case, it should send the first message in plaintext with a special whitespace character sequence appended. If the other end (Profanity in this case) supports the opportunistic policy it should display the plaintext message and then attempt to initiate the session.  Neither end should send encrypted messages until the session has been started.

Profanity by default has OTR policy set to "manual" which means it will not allow other clients to start the session with "opportunistic", they must start it manually. But even in this case, you should never see the ciphertext of an encrypted OTR message.

Apologies if you know all of the above.

Setting Psi+ to be opportunistic (to try to imitate Conversations behavior), things still work as expected, only plaintext is sent, and no session is started.

Changing Profanity to allow the "opportunistic" policy:

```
/otr policy opportunistic
```

And testing again with Psi+ things still work as expected, the first message is plaintext, then the session starts and further messages are encrypted/decrypted correctly.

Have you mentioned this to anyone on the Conversations team? Not yet suggesting it's a Conversations issue, but I can't currently recreate with a different client and they might be able to help.

**Comment by boothj5** [comment] 2015-09-07 20:16
The console shows the following when sending an opportunistic message from Psi+, and Profanity is configured to support it.

```
OTR Whitespace pattern detected. Attempting to start OTR session...
<< incoming from user@server.org/Psi+ (5)
user@server.org started an OTR session (5).
```
If you don't see the first line, it sounds like Conversations is not sending the whitespace tag.

**Comment by boothj5** [comment] 2015-09-07 21:23
After downloading and testing with Conversations, I've found the following:

1) Conversations: Enable OTR
2) Conversations: Send message
3) Other client: OTR automatically enabled
4) Conversations: Send message
5) Other client: Nothing is displayed
6) Conversations: Send another message
7) Other client: Message is displayed correctly

I tested with "Other client" being both Profanity and Psi+, so it appears there may be something wrong with the way Conversations starts OTR.

1) Conversations -> Profanity : Issue present
2) Conversations -> Psi+ : Issue present
3) Psi -> Profanity : No issue
4) Profanity -> Psi+ : No issue

Using debug logs with Profanity, the first message I get from Conversations is:

```
<message type="chat" to="me@server/resource" from="them@server/resource"><body>?OTRv23?I would like to start a private (OTR encrypted) conversation but your client doesn’t seem to support that</body><private xmlns="urn:xmpp:carbons:2"/><no-copy xmlns="urn:xmpp:hints"/></message>
```

Followed by what looks like OTR session initialisation.

I will raise an issue at Conversations.

**Comment by boothj5** [comment] 2015-09-07 23:15
After upgrading to the latest Conversations, I've managed to replicate the issue.

For some reason, the first OTR message from Conversations has a delayed timestamp attached to it.  No other OTR messages have this element.

```
<delay xmlns="urn:xmpp:delay" stamp="2015-09-07T22:23:18.433Z"/>
```

In profanity delayed messages are never passed through the OTR code, since only messages within a live OTR session can be decrypted, and trying to decrypt a delayed message from a previous OTR session would fail.

However this is a slightly odd case, the message is not actually delayed in this sense, but the delayed element has been attached.

I've been having a conversation in the conversations (no pun intended) chat room, and will probably make profanity deal with this case, even though it's very rare.

**Comment by boothj5** [comment] 2015-09-08 19:28
Should now be working in master, if you're able to build latest and test, let me know if it's fixed for you.

Thanks.

**Comment by quite** [comment] 2015-09-11 07:59
Yay! First message decrypted correctly.

**Comment by quite** [comment] 2015-09-11 08:15
As I mentioned, I have had problems with a contact using agl/xmpp-client. We (prefer) to talk exclusively using otr, and it seemed that when he disappeared, for some reason went offline, without ending the otr session properly (which agl-client would normally do upon a clean /quit), he will not be able to set up a new otr session to my (still) running profanity instance. I would not see *anything* from him until he gave me heads-up on some other channel, and I do /otr end /close or even /quit.

It seems like this fix *might* have affected, possibly even solved this issue. Can I make profanity more verbose about otr sessions? Can it display the "session id" when a (new) session has been negotiated? It seems agl-client does that, and it might be helpful, perhaps even by default. My contact is currently able to make the agl-client initiate a new session while we already have one running. It works, and it's a very good sign, but in profanity I see nothing special when it happens.

**Comment by boothj5** [comment] 2015-09-11 12:57
Closing this as the conversations issue is fixed.

I've also raised two separate issues, if you want to comment/clarify on them. 

#611
#612

**Closed by boothj5** 2015-09-11 12:57 UTC
Labels: bug, medium
