### ISSUE TITLE
Allow reloading the roster

### ISSUE THREAD

**Issue by strugee** [boothj5/profanity#748] opened 2016-02-28 07:32 UTC
I have a long-running Profanity instance. I added someone to my roster in Conversations on my phone, but they didn't show up in Profanity until I restarted. There should be a way to reload the roster or, better, watch for changes.

**Comment by boothj5** [comment] 2016-02-28 15:45
Can't recreate this at the moment.

When I add or remove a contact using another client (Psi+ in my case) I immediately get the following messages in the Profanity console:

```
Roster item removed: user@server.org
Roster item added: user@server.org (Nickname)
```

And the new contact appears in the roster panel. Also if I change the nickname in another client, the change is reflected in the roster panel straight away.

I'm running against master (fbd913ec626d8436ea4efdde4ffc8090a3b52cfc), which version are you running?

Also, I know conversations integrates with the phone's address book, but I don't know how this interacts with the servers, from the Conversations readme:

"The address book integration was designed to protect your privacy. Conversations neither uploads contacts from your address book to your server nor fills your address book with unnecessary contacts from your online roster."

One way to see what is going on:

1) Run profanity in debug mode `profanity -l DEBUG`
2) Add a contact with conversations the same way you did before
3) Attach logs here (removing any personal information), log location can be found by running `/log`
4) If a roster update was received by profanity in the logs, then the problem appears to be in profanity
5) If no roster update was received, then the behaviour is due to Conversations not sending contact details to the server.

**Comment by boothj5** [comment] 2016-02-28 15:54
Also tested against 0.4.7 and cannot recreate.

**Comment by strugee** [comment] 2016-02-29 06:51
Hmm, weird. It'll be a little while before I can really look at this, but I'm realizing now it may have been my client being disconnected or something. :/

**Comment by boothj5** [comment] 2016-03-07 16:46
Closing this issue for now, as profanity syncs with the servers roster.  Please repoen or create another issue if you have any further issues.

**Closed by boothj5** 2016-03-07 16:46 UTC
