### ISSUE TITLE
Stack smashing with 0.4.7 on debian 8

### ISSUE THREAD

**Issue by clux** [boothj5/profanity#693] opened 2015-12-10 18:10 UTC
Tried compiling latest on debian 8 to get a newer version. Got it built, but it exits with stack smashing error.

These are the dependencies I built with:

```sh
# what seemed like the correct dependencies available on stable:
sudo apt-get install -y \
  autoconf \
  libssl-dev \
  libstrophe-dev \
  libncursesw5-dev \
  libcurl4-gnutls-dev \
  libreadline-dev \
  libotr5-dev
# checkout 0.4.7 release and cd into it
mkdir m4
./bootstrap.sh
./configure --enable-otr
make -j8
./profanity -a anyxmppacc
```

```
*** stack smashing detected ***: ./profanity terminated
                                                       Segmentation fault
```

Happens during connect. Backtrace is not particularly helpful either:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff1151688 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) bt
#0  0x00007ffff1151688 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007ffff11526f8 in _Unwind_Backtrace () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#2  0x00007ffff5aecf46 in __GI___backtrace (array=<optimized out>, size=64) at ../sysdeps/x86_64/backtrace.c:109
#3  0x00007ffff5a19d62 in backtrace_and_maps (do_abort=0, do_abort@entry=2, written=false, fd=8) at ../sysdeps/unix/sysv/linux/libc_fatal.c:47
#4  0x00007ffff5a6d1ff in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff5b5da2b "*** %s ***: %s terminated\n") at ../sysdeps/posix/libc_fatal.c:172
#5  0x00007ffff5af04c7 in __GI___fortify_fail (msg=msg@entry=0x7ffff5b5da13 "stack smashing detected") at fortify_fail.c:31
#6  0x00007ffff5af0490 in __stack_chk_fail () at stack_chk_fail.c:28
#7  0x00007ffff62e05af in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#8  0x00007fff00000000 in ?? ()
#9  0x00007fffffffc310 in ?? ()
#10 0x00007fffffffc3e0 in ?? ()
#11 0x00007fffffffc230 in ?? ()
#12 0x0000104af7fc8030 in ?? ()
#13 0x0001000100000008 in ?? ()
#14 0x00007ffff6204bf0 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#15 0x0000000000000005 in ?? ()
#16 0x0000000000000409 in ?? ()
#17 0x0000000000000001 in ?? ()
#18 0x00000000000021b6 in ?? ()
#19 0x0000000000000000 in ?? ()
```
 gcc 4.9.2

**Comment by boothj5** [comment] 2015-12-10 20:48
Duplicate of #662 

You could try to install the latest code from https://github.com/strophe/libstrophe rather than using the supplied package and see if the issue is resolved.

**Closed by boothj5** 2015-12-10 20:48 UTC

**Comment by clux** [comment] 2015-12-11 10:48
Thanks. Confirming this solved the issue.
