### ISSUE TITLE
prof_whole_occurrences_tests unittest fails on armel/armhf/mips/mipsel

### ISSUE THREAD

**Issue by jacksgt** [boothj5/profanity#901] opened 2017-01-25 21:06 UTC
Hi,

the `prof_whole_occurrences_tests` unittest fails on the following architectures:
* armel
* armhf
* mips
* mipsel
* powerpc
* hppa

```
=======================================
   profanity 0.5.0: ./test-suite.log
=======================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/unittests/unittests
===============================

[==========] Running 412 test(s).
[ RUN      ] replace_one_substr
[       OK ] replace_one_substr
[ RUN      ] replace_one_substr_beginning
[       OK ] replace_one_substr_beginning
[ RUN      ] replace_one_substr_end
[       OK ] replace_one_substr_end
[ RUN      ] replace_two_substr
[       OK ] replace_two_substr
[ RUN      ] replace_char
[       OK ] replace_char
[ RUN      ] replace_when_none
[       OK ] replace_when_none
[ RUN      ] replace_when_match
[       OK ] replace_when_match
[ RUN      ] replace_when_string_empty
[       OK ] replace_when_string_empty
[ RUN      ] replace_when_string_null
[       OK ] replace_when_string_null
[ RUN      ] replace_when_sub_empty
[       OK ] replace_when_sub_empty
[ RUN      ] replace_when_sub_null
[       OK ] replace_when_sub_null
[ RUN      ] replace_when_new_empty
[       OK ] replace_when_new_empty
[ RUN      ] replace_when_new_null
[       OK ] replace_when_new_null
[ RUN      ] test_online_is_valid_resource_presence_string
[       OK ] test_online_is_valid_resource_presence_string
[ RUN      ] test_chat_is_valid_resource_presence_string
[       OK ] test_chat_is_valid_resource_presence_string
[ RUN      ] test_away_is_valid_resource_presence_string
[       OK ] test_away_is_valid_resource_presence_string
[ RUN      ] test_xa_is_valid_resource_presence_string
[       OK ] test_xa_is_valid_resource_presence_string
[ RUN      ] test_dnd_is_valid_resource_presence_string
[       OK ] test_dnd_is_valid_resource_presence_string
[ RUN      ] test_available_is_not_valid_resource_presence_string
[       OK ] test_available_is_not_valid_resource_presence_string
[ RUN      ] test_unavailable_is_not_valid_resource_presence_string
[       OK ] test_unavailable_is_not_valid_resource_presence_string
[ RUN      ] test_blah_is_not_valid_resource_presence_string
[       OK ] test_blah_is_not_valid_resource_presence_string
[ RUN      ] test_p_sha1_hash1
[       OK ] test_p_sha1_hash1
[ RUN      ] test_p_sha1_hash2
[       OK ] test_p_sha1_hash2
[ RUN      ] test_p_sha1_hash3
[       OK ] test_p_sha1_hash3
[ RUN      ] test_p_sha1_hash4
[       OK ] test_p_sha1_hash4
[ RUN      ] test_p_sha1_hash5
[       OK ] test_p_sha1_hash5
[ RUN      ] test_p_sha1_hash6
[       OK ] test_p_sha1_hash6
[ RUN      ] test_p_sha1_hash7
[       OK ] test_p_sha1_hash7
[ RUN      ] utf8_display_len_null_str
[       OK ] utf8_display_len_null_str
[ RUN      ] utf8_display_len_1_non_wide
[       OK ] utf8_display_len_1_non_wide
[ RUN      ] utf8_display_len_1_wide
[       OK ] utf8_display_len_1_wide
[ RUN      ] utf8_display_len_non_wide
[       OK ] utf8_display_len_non_wide
[ RUN      ] utf8_display_len_wide
[ RUN      ] parse_options_when_unknown_opt_sets_error
[       OK ] parse_options_when_unknown_opt_sets_error
[ RUN      ] parse_options_with_duplicated_option_sets_error
[       OK ] parse_options_with_duplicated_option_sets_error
[ RUN      ] empty_list_when_none_added
[       OK ] empty_list_when_none_added
[ RUN      ] contains_one_element
[       OK ] contains_one_element
[ RUN      ] first_element_correct
[       OK ] first_element_correct
[ RUN      ] contains_two_elements
[       OK ] contains_two_elements
[ RUN      ] first_and_second_elements_correct
[       OK ] first_and_second_elements_correct
[ RUN      ] contains_three_elements
[       OK ] contains_three_elements
[ RUN      ] first_three_elements_correct
[       OK ] first_three_elements_correct
[ RUN      ] add_twice_at_beginning_adds_once
[       OK ] add_twice_at_beginning_adds_once
[ RUN      ] add_twice_in_middle_adds_once
[       OK ] add_twice_in_middle_adds_once
[ RUN      ] add_twice_at_end_adds_once
[       OK ] add_twice_at_end_adds_once
[ RUN      ] find_first_exists
[       OK ] find_first_exists
[ RUN      ] find_second_exists
[       OK ] find_second_exists
[ RUN      ] find_third_exists
[       OK ] find_third_exists
[ RUN      ] find_returns_null
[       OK ] find_returns_null
[ RUN      ] find_on_empty_returns_null
[       OK ] find_on_empty_returns_null
[ RUN      ] find_twice_returns_second_when_two_match
[       OK ] find_twice_returns_second_when_two_match
[ RUN      ] find_five_times_finds_fifth
[       OK ] find_five_times_finds_fifth
[ RUN      ] find_twice_returns_first_when_two_match_and_reset
[       OK ] find_twice_returns_first_when_two_match_and_reset
[ RUN      ] add_contact_with_no_group
[       OK ] add_contact_with_no_group
[ RUN      ] add_contact_with_group
[       OK ] add_contact_with_group
[ RUN      ] add_contact_with_two_groups
[       OK ] add_contact_with_two_groups
[ RUN      ] add_contact_with_three_groups
[       OK ] add_contact_with_three_groups
[ RUN      ] add_contact_with_three_groups_update_adding_two
[       OK ] add_contact_with_three_groups_update_adding_two
[ RUN      ] add_contact_with_three_groups_update_removing_one
[       OK ] add_contact_with_three_groups_update_removing_one
[ RUN      ] add_contact_with_three_groups_update_removing_two
[       OK ] add_contact_with_three_groups_update_removing_two
[ RUN      ] add_contact_with_three_groups_update_removing_three
[       OK ] add_contact_with_three_groups_update_removing_three
[ RUN      ] add_contact_with_three_groups_update_two_new
[       OK ] add_contact_with_three_groups_update_two_new
[ RUN      ] add_remove_contact_groups
[       OK ] add_remove_contact_groups
[ RUN      ] add_contacts_with_different_groups
[       OK ] add_contacts_with_different_groups
[ RUN      ] add_contacts_with_same_groups
[       OK ] add_contacts_with_same_groups
[ RUN      ] add_contacts_with_overlapping_groups
[       OK ] add_contacts_with_overlapping_groups
[ RUN      ] remove_contact_with_remaining_in_group
[       OK ] remove_contact_with_remaining_in_group
[ RUN      ] returns_false_when_chat_session_does_not_exist
[       OK ] returns_false_when_chat_session_does_not_exist
[ RUN      ] creates_chat_session_on_recipient_activity
[       OK ] creates_chat_session_on_recipient_activity
[ RUN      ] replaces_chat_session_on_recipient_activity_with_different_resource
[       OK ] replaces_chat_session_on_recipient_activity_with_different_resource
[ RUN      ] removes_chat_session
[       OK ] removes_chat_session
[ RUN      ] cmd_connect_shows_message_when_disconnecting
[       OK ] cmd_connect_shows_message_when_disconnecting
[ RUN      ] cmd_connect_shows_message_when_connecting
[       OK ] cmd_connect_shows_message_when_connecting
[ RUN      ] cmd_connect_shows_message_when_connected
[       OK ] cmd_connect_shows_message_when_connected
[ RUN      ] cmd_connect_when_no_account
[       OK ] cmd_connect_when_no_account
[ RUN      ] cmd_connect_fail_message
[       OK ] cmd_connect_fail_message
[ RUN      ] cmd_connect_lowercases_argument
[       OK ] cmd_connect_lowercases_argument
[ RUN      ] cmd_connect_asks_password_when_not_in_account
[       OK ] cmd_connect_asks_password_when_not_in_account
[ RUN      ] cmd_connect_shows_usage_when_no_server_value
[       OK ] cmd_connect_shows_usage_when_no_server_value
[ RUN      ] cmd_connect_shows_message_when_connecting_with_account
[       OK ] cmd_connect_shows_message_when_connecting_with_account
[ RUN      ] cmd_connect_connects_with_account
[       OK ] cmd_connect_connects_with_account
[ RUN      ] cmd_connect_shows_usage_when_server_no_port_value
[       OK ] cmd_connect_shows_usage_when_server_no_port_value
[ RUN      ] cmd_connect_shows_usage_when_no_port_value
[       OK ] cmd_connect_shows_usage_when_no_port_value
[ RUN      ] cmd_connect_shows_usage_when_port_no_server_value
[       OK ] cmd_connect_shows_usage_when_port_no_server_value
[ RUN      ] cmd_connect_shows_message_when_port_0
[       OK ] cmd_connect_shows_message_when_port_0
[ RUN      ] cmd_connect_shows_message_when_port_minus1
[       OK ] cmd_connect_shows_message_when_port_minus1
[ RUN      ] cmd_connect_shows_message_when_port_65536
[       OK ] cmd_connect_shows_message_when_port_65536
[ RUN      ] cmd_connect_shows_message_when_port_contains_chars
[       OK ] cmd_connect_shows_message_when_port_contains_chars
[ RUN      ] cmd_connect_with_server_when_provided
[       OK ] cmd_connect_with_server_when_provided
[ RUN      ] cmd_connect_with_port_when_provided
[       OK ] cmd_connect_with_port_when_provided
[ RUN      ] cmd_connect_with_server_and_port_when_provided
[       OK ] cmd_connect_with_server_and_port_when_provided
[ RUN      ] cmd_connect_shows_usage_when_server_provided_twice
[       OK ] cmd_connect_shows_usage_when_server_provided_twice
[ RUN      ] cmd_connect_shows_usage_when_port_provided_twice
[       OK ] cmd_connect_shows_usage_when_port_provided_twice
[ RUN      ] cmd_connect_shows_usage_when_invalid_first_property
[       OK ] cmd_connect_shows_usage_when_invalid_first_property
[ RUN      ] cmd_connect_shows_usage_when_invalid_second_property
[       OK ] cmd_connect_shows_usage_when_invalid_second_property
[ RUN      ] cmd_rooms_shows_message_when_disconnected
[ RUN      ] cmd_presence_shows_usage_when_bad_console_setting
[       OK ] cmd_presence_shows_usage_when_bad_console_setting
[ RUN      ] cmd_presence_shows_usage_when_bad_chat_setting
[       OK ] cmd_presence_shows_usage_when_bad_chat_setting
[ RUN      ] cmd_presence_shows_usage_when_bad_muc_setting
[       OK ] cmd_presence_shows_usage_when_bad_muc_setting
[ RUN      ] cmd_presence_console_sets_all
[       OK ] cmd_presence_console_sets_all
[ RUN      ] cmd_presence_console_sets_online
[       OK ] cmd_presence_console_sets_online
[ RUN      ] cmd_presence_console_sets_none
[       OK ] cmd_presence_console_sets_none
[ RUN      ] cmd_presence_chat_sets_all
[       OK ] cmd_presence_chat_sets_all
[ RUN      ] cmd_presence_chat_sets_online
[       OK ] cmd_presence_chat_sets_online
[ RUN      ] cmd_presence_chat_sets_none
[       OK ] cmd_presence_chat_sets_none
[ RUN      ] cmd_presence_room_sets_all
[       OK ] cmd_presence_room_sets_all
[ RUN      ] cmd_presence_room_sets_online
[       OK ] cmd_presence_room_sets_online
[ RUN      ] cmd_presence_room_sets_none
[       OK ] cmd_presence_room_sets_none
[ RUN      ] statuses_console_defaults_to_all
[       OK ] statuses_console_defaults_to_all
[ RUN      ] statuses_chat_defaults_to_all
[       OK ] statuses_chat_defaults_to_all
[ RUN      ] statuses_muc_defaults_to_all
[       OK ] statuses_muc_defaults_to_all
[ RUN      ] console_shows_online_presence_when_set_online
[       OK ] console_shows_online_presence_when_set_online
[ RUN      ] console_shows_online_presence_when_set_all
[       OK ] console_shows_online_presence_when_set_all
[ RUN      ] console_shows_dnd_presence_when_set_all
[       OK ] console_shows_dnd_presence_when_set_all
[ RUN      ] handle_offline_removes_chat_session
[       OK ] handle_offline_removes_chat_session
[ RUN      ] lost_connection_clears_chat_sessions
[       OK ] lost_connection_clears_chat_sessions
[ RUN      ] cmd_alias_add_shows_usage_when_no_args
[       OK ] cmd_alias_add_shows_usage_when_no_args
[ RUN      ] cmd_alias_add_shows_usage_when_no_value
[       OK ] cmd_alias_add_shows_usage_when_no_value
[ RUN      ] cmd_alias_remove_shows_usage_when_no_args
[       OK ] cmd_alias_remove_shows_usage_when_no_args
[ RUN      ] cmd_alias_show_usage_when_invalid_subcmd
[       OK ] cmd_alias_show_usage_when_invalid_subcmd
[ RUN      ] cmd_alias_add_adds_alias
[       OK ] cmd_alias_add_adds_alias
[ RUN      ] cmd_alias_add_shows_message_when_exists
[       OK ] cmd_alias_add_shows_message_when_exists
[ RUN      ] cmd_alias_remove_removes_alias
[       OK ] cmd_alias_remove_removes_alias
[ RUN      ] cmd_alias_remove_shows_message_when_no_alias
[       OK ] cmd_alias_remove_shows_message_when_no_alias
[ RUN      ] cmd_alias_list_shows_all_aliases
[       OK ] cmd_alias_list_shows_all_aliases
[ RUN      ] test_muc_invites_add
[       OK ] test_muc_invites_add
[ RUN      ] test_muc_remove_invite
[       OK ] test_muc_remove_invite
[ RUN      ] test_muc_invites_count_0
[       OK ] test_muc_invites_count_0
[ RUN      ] test_muc_invites_count_5
[       OK ] test_muc_invites_count_5
[ RUN      ] test_muc_room_is_not_active
[       OK ] test_muc_room_is_not_active
[ RUN      ] test_muc_active
[       OK ] test_muc_active
[ RUN      ] cmd_bookmark_shows_message_when_disconnected
[       OK ] cmd_bookmark_shows_message_when_disconnected
[ RUN      ] cmd_bookmark_shows_message_when_disconnecting
[       OK ] cmd_bookmark_shows_message_when_disconnecting
[ RUN      ] cmd_bookmark_shows_message_when_connecting
[       OK ] cmd_bookmark_shows_message_when_connecting
[ RUN      ] cmd_bookmark_shows_usage_when_no_args
[       OK ] cmd_bookmark_shows_usage_when_no_args
[ RUN      ] cmd_bookmark_list_shows_bookmarks
[       OK ] cmd_bookmark_list_shows_bookmarks
[ RUN      ] cmd_bookmark_add_shows_message_when_invalid_jid
[       OK ] cmd_bookmark_add_shows_message_when_invalid_jid
[ RUN      ] cmd_bookmark_add_adds_bookmark_with_jid
[       OK ] cmd_bookmark_add_adds_bookmark_with_jid
[ RUN      ] cmd_bookmark_add_adds_bookmark_with_jid_nick
[       OK ] cmd_bookmark_add_adds_bookmark_with_jid_nick
[ RUN      ] cmd_bookmark_add_adds_bookmark_with_jid_autojoin
[       OK ] cmd_bookmark_add_adds_bookmark_with_jid_autojoin
[ RUN      ] cmd_bookmark_add_adds_bookmark_with_jid_nick_autojoin
[ RUN      ] add_value_adds_when_some
[       OK ] add_value_adds_when_some
[ RUN      ] add_value_adds_when_exists
[       OK ] add_value_adds_when_exists
[ RUN      ] remove_value_does_nothing_when_none
[       OK ] remove_value_does_nothing_when_none
[ RUN      ] remove_value_does_nothing_when_doesnt_exist
[       OK ] remove_value_does_nothing_when_doesnt_exist
[ RUN      ] remove_value_removes_when_one
[       OK ] remove_value_removes_when_one
[ RUN      ] remove_value_removes_when_many
[       OK ] remove_value_removes_when_many
[ RUN      ] remove_text_multi_value_does_nothing_when_none
[       OK ] remove_text_multi_value_does_nothing_when_none
[ RUN      ] remove_text_multi_value_does_nothing_when_doesnt_exist
[       OK ] remove_text_multi_value_does_nothing_when_doesnt_exist
[ RUN      ] remove_text_multi_value_removes_when_one
[       OK ] remove_text_multi_value_removes_when_one
[ RUN      ] remove_text_multi_value_removes_when_many
[       OK ] remove_text_multi_value_removes_when_many
[ RUN      ] clears_chat_sessions
[       OK ] clears_chat_sessions
[ RUN      ] prof_partial_occurrences_tests
[       OK ] prof_partial_occurrences_tests
[ RUN      ] prof_whole_occurrences_tests
_lists_equal(prof_occurrences("boothj5", "boothj5", 0, TRUE, &actual), expected)
tests/unittests/test_common.c:441: error: Failure!
[  FAILED  ] prof_whole_occurrences_tests
[ RUN      ] returns_no_commands
[       OK ] returns_no_commands
[ RUN      ] returns_commands
[       OK ] returns_commands
[ RUN      ] returns_empty_list_when_none
[       OK ] returns_empty_list_when_none
[ RUN      ] returns_added_feature
[       OK ] returns_added_feature
[ RUN      ] resets_features_on_close
[       OK ] resets_features_on_close
[ RUN      ] returns_all_added_features
[       OK ] returns_all_added_features
[ RUN      ] does_not_add_duplicate_feature
[       OK ] does_not_add_duplicate_feature
[ RUN      ] removes_plugin_features
[       OK ] removes_plugin_features
[ RUN      ] does_not_remove_feature_when_more_than_one_reference
[       OK ] does_not_remove_feature_when_more_than_one_reference
[==========] 412 test(s) run.
[  PASSED  ] 411 test(s).
[  FAILED  ] 1 test(s), listed below:
[  FAILED  ] prof_whole_occurrences_tests
FAIL tests/unittests/unittests (exit status: 1)
```

When removing the following line (I tried by commenting the line with `//`) from test/unittests/test_common.c, the problem disappears (at least on armhf):
```
assert_true(_lists_equal(prof_occurrences("boothj5", "boothj5",      0, TRUE, &actual), expected)); g_slist_free(actual); actual = NULL;
```
https://github.com/boothj5/profanity/blob/master/tests/unittests/test_common.c#L441

Please see https://buildd.debian.org/status/logs.php?pkg=profanity&ver=0.5.0-0.1

**Comment by boothj5** [comment] 2017-01-25 21:40
For info, the code under test is:

```
GSList*
prof_occurrences(const char *const needle, const char *const haystack, int offset, gboolean whole_word, GSList **result)
{
    if (needle == NULL || haystack == NULL) {
        return *result;
    }

    if (g_str_has_prefix(&haystack[offset], needle)) {
        if (whole_word) {
            char *prev = g_utf8_prev_char(&haystack[offset]);
            char *next = g_utf8_next_char(&haystack[offset] + strlen(needle) - 1);
            gunichar prevu = g_utf8_get_char(prev);
            gunichar nextu = g_utf8_get_char(next);
            if (!g_unichar_isalnum(prevu) && !g_unichar_isalnum(nextu)) {
                *result = g_slist_append(*result, GINT_TO_POINTER(offset));
            }
        } else {
            *result = g_slist_append(*result, GINT_TO_POINTER(offset));
        }
    }

    if (haystack[offset+1] != '\0') {
        *result = prof_occurrences(needle, haystack, offset+1, whole_word, result);
    }

    return *result;
}
```

The difference between the failing test `prof_whole_occurrences_tests` and the previous test that passes `prof_partial_occurrences_tests`, is this path of execution `whole_word == TRUE`:

```
        if (whole_word) {
            char *prev = g_utf8_prev_char(&haystack[offset]);
            char *next = g_utf8_next_char(&haystack[offset] + strlen(needle) - 1);
            gunichar prevu = g_utf8_get_char(prev);
            gunichar nextu = g_utf8_get_char(next);
            if (!g_unichar_isalnum(prevu) && !g_unichar_isalnum(nextu)) {
                *result = g_slist_append(*result, GINT_TO_POINTER(offset));
            }
```

**Comment by jacksgt** [comment] 2017-01-25 21:41
```
GSList*
prof_occurrences(const char *const needle, const char *const haystack, int offset, gboolean whole_word, GSList **result)
{
    if (needle == NULL || haystack == NULL) {
        return *result;
    }

    if (g_str_has_prefix(&haystack[offset], needle)) {
        if (whole_word) {
            char *prev = g_utf8_prev_char(&haystack[offset]);
            char *next = g_utf8_next_char(&haystack[offset] + strlen(needle) - 1);
            gunichar prevu = g_utf8_get_char(prev);
            gunichar nextu = g_utf8_get_char(next);
            if (!g_unichar_isalnum(prevu) && !g_unichar_isalnum(nextu)) {
                *result = g_slist_append(*result, GINT_TO_POINTER(offset));
            }
        } else {
            *result = g_slist_append(*result, GINT_TO_POINTER(offset));
        }
    }

    if (haystack[offset+1] != '\0') {
        *result = prof_occurrences(needle, haystack, offset+1, whole_word, result);
    }

    return *result;
}
```

I don't fully understand how this function works, but the `next`-line looks a bit weird to me:
```
char *prev = g_utf8_prev_char(&haystack[offset]);
char *next = g_utf8_next_char(&haystack[offset] + strlen(needle) - 1);
```
`haystack` and `needle` are `boothj5` (7 chars without null byte) and offset is 0.
In the first recursion, prev is `b`, but next gets calculated as haystack[0+7-1], therefore being `5` .

**Comment by boothj5** [comment] 2017-01-25 22:10
I just saw yours too!

I think that piece of code is ok, its getting the last character `5` and then using GLib to get the next utf8 character after `5`.

The issue is probably the usage of `1` throughout this routine.  To handle utf8 it shouldn't be assuming every character is 1 byte long.

This is currently guess work, but maybe on the failing architectures,  is it possible that they use two bytes for a non utf8 character?

I'm going to attempt to add some utf8 tests to prove the theory.

**Comment by jacksgt** [comment] 2017-01-25 22:19
> This is currently guess work, but maybe on the failing architectures, is it possible that they use two bytes for a non utf8 character?
Possibly, but in this case the test compares `"boothj5"` with `"boothj5"`, so there aren't even any non-ASCII chars.

**Comment by boothj5** [comment] 2017-01-26 01:03
I've made some fixes to use the length of the char in bytes rather than assuming a length of 1.  I'm not sure if this was the issue, but it was definitely causing problem when I tested with some utf8 characters.

What's the easiest way to test on one of these architectures?

**Comment by tdi** [comment] 2017-01-29 11:11
I can try to build it on some of the Debian machines that have these architectures and get back to you.

**Comment by jacksgt** [comment] 2017-01-29 21:05
Not exactly 'easy', but you could also spin up a VM (e.g. with VirtualBox) and test it there.

I first tested it on my Cubietruck, but compiling and testing there was no fun :-/

**Comment by boothj5** [comment] 2017-01-29 21:11
Interesting, not heard of the Cubietruck before.

I'll see if I can find a VirtualBox image,  I have a project for this kind of thing: https://github.com/boothj5/profanity-vms

**Comment by adconrad** [comment] 2017-04-12 13:37
For the curious, no, the above commit does not fix the armhf testsuite failure:

https://launchpad.net/ubuntu/+source/profanity/0.5.0-0.1ubuntu1

**Comment by diegoroversi** [comment] 2017-04-28 18:47
The problem is here:

`char *prev = g_utf8_prev_char(&haystack[offset]);`

If offset is 0, then you are trying to read before the start of the string. The contents of haystack[-1] is "undefined" and can be anything. On armhf, during my test, is usually a 'o' that is a valid character, so the test isalnum('o') is true and condition about "whole word" fail. On amd64 and x86 architecture it works only by sheer luck.

You should check that offset is >0 before reading prev.  Something like this:

```
gboolean previsalnum=0;
if (offset >0) {
  char *prev= g_utf8_prev_char(&haystack[offset]);
  gunichar prevu = g_utf8_get_char(prev);
  previsalnum=isalnum(prevu);
}
```
  
This is not perfect. There is some corner case, if haystack is not a valid utf-8, and g_utf8_prev_char can go before the begin of the string. But should work fine, with "sane" utf-8 strings.

**Comment by diegoroversi** [comment] 2017-04-28 19:10
Also, it's always tricky to do this kind of things right. I suggest to use some library like pcre2, or ICU, that support utf-8 and regular expression. 

And maybe some program to test out of array access, like valgrind.

**Comment by boothj5** [comment] 2017-04-28 20:55
@diegoroversi thanks for looking into this.

The code you reference has changed in master, although the issue was still occurring according to comments above.

I have just made another change, previously it was using [g_utf8_prev_char()](https://developer.gnome.org/glib/2.40/glib-Unicode-Manipulation.html#g-utf8-prev-char) to get the previous char, after looking at the documentation, it appears that [g_utf8_find_prev_char()](https://developer.gnome.org/glib/2.40/glib-Unicode-Manipulation.html#g-utf8-find-prev-char) is the safe version for when calling against the first character.  Commit https://github.com/boothj5/profanity/commit/3e18aab9f38fad3cd971ec09684f7e03f299cc87 now uses the correct function and checks if there is a previous character.

I'd prefer to use the Glib utf8 functions rather than adding another dependency if possible, however if it can't be solved with Glib then it makes sense to use a full utf8 library.

If you have a chance to try the latest code in master, I'd be interested to see if this fixes the tests.

As a side note, one of the tests fails when run from my IDE (Codelite), but works on the command line when running make check-unit, I think this may be an issue with character encoding setup in the IDE, but not 100% sure.

**Comment by diegoroversi** [comment] 2017-04-29 10:28
I tried your code, but gcc 6 give me the following error:

```
src/common.c: In function 'prof_occurrences':
src/common.c:470:31: error: initialization makes integer from pointer without a cast [-Werror=int-conversion]
             gunichar before = NULL;
                               ^~~~
src/common.c:476:30: error: initialization makes integer from pointer without a cast [-Werror=int-conversion]
             gunichar after = NULL;
                              ^~~~
cc1: all warnings being treated as errors

```

NULL is a char *, so it gives you a error if you do a implict cast to integer.  It's ok to replace NULL with 0.

Now the previous test succeded. But fail to this:
`
tests/unittests/test_common.c:449: error: Failure!`

**Comment by boothj5** [comment] 2017-04-29 19:35
Fixed the warning, NULL is actually a void * but it still makes sense.

The failure you're now seeing is the same as what happens when I run tests in Codelite.  After adding some debug, I've found that the codeset was not being set properly when running tests from the IDE:

```
Charset information:
  LANG:       en_GB.UTF-8
  CODESET:    ANSI_X3.4-1968
  MB_CUR_MAX: 1
  MB_LEN_MAX: 16
```

By setting it explicitly in the tests, all are now passing in Codelite.  This may be the same issue as on the arm chipsets:

```
Charset information:
  LANG:       en_GB.UTF-8
  CODESET:    UTF-8
  MB_CUR_MAX: 6
  MB_LEN_MAX: 16
```

Again, if you have time to try it, let me know if this fixes the broken test you're currently seeing.

Profanity needs to be run in an environment with a UTF8 character encoding (http://profanity.im/faq.html#utf8encoding) so I think this issue is only with the tests.

Thanks for helping, I still don't have an environment to try this on, so it's very useful.

**Comment by diegoroversi** [comment] 2017-04-30 05:58
Yes, with "export LANG=en_GB.UTF-8" (and after installing the right locales <grin>) , now it pass all the tests.

It would be nice making a test, at the beginning, to check that there is the correct encoding, and abort otherwise.

PS: if you need to test on different architecture, there is a nice tutorial for emulating a arm with qemu:

https://translatedcode.wordpress.com/2016/11/03/installing-debian-on-qemus-32-bit-arm-virt-board/

Some hints: add cache=unsafe to have a nice speedup on I/O. And it's quite slow: installing a base debian require some hours. But after that is quite usable, ymmv.

**Comment by boothj5** [comment] 2017-05-04 22:24
@jacksgt if you have a chance, let me know if the current code and LANG setting fixes the issue for you too. If so, I'll look at failing the tests with a useful message and close this issue.

**Comment by jubalh** [comment] 2019-04-15 11:17
For the tests to work we need an UTF-8 locale installed and set on the testing machine. We needed to do this on the travis build too: https://github.com/boothj5/profanity/pull/1059/commits/0857b5ee4e40480cf9a3c543f93b5240f0d11b04

0.6.0 Debian tests for all archs look good: https://buildd.debian.org/status/logs.php?pkg=profanity&ver=0.6.0-1&suite=sid

**Closed by jubalh** 2019-04-15 11:17 UTC
Labels: bug
