### ISSUE TITLE
Can't build on OS X El Capitan

### ISSUE THREAD

**Issue by tristan-k** [boothj5/profanity#812] opened 2016-05-23 13:49 UTC
@boothj5 @robsalasco

```
$ uname -a
Darwin tk-pb4540s-macosx.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

$ brew tap robsalasco/homebrew-profanity
$ brew install profanity --HEAD
==> Cloning https://github.com/boothj5/profanity.git
Updating /Library/Caches/Homebrew/profanity--git
==> Checking out branch master
==> ./bootstrap.sh
Last 15 lines from /Volumes/Home/tristank/Library/Logs/Homebrew/profanity/01.bootstrap.sh:

./bootstrap.sh

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
configure.ac:15: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues
```

Then after installing `$ brew install libstrophe --HEAD` manually.

```
$ brew install profanity --HEAD
==> Cloning https://github.com/boothj5/profanity.git
Updating /Library/Caches/Homebrew/profanity--git
==> Checking out branch master
==> ./bootstrap.sh
Last 15 lines from /Volumes/Home/tristank/Library/Logs/Homebrew/profanity/01.bootstrap.sh:
2016-05-23 15:54:49 +0200

./bootstrap.sh

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: glibtoolize --copy --force
Can't exec "glibtoolize": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 345, <GEN2> line 7.
autoreconf: failed to run glibtoolize: No such file or directory
autoreconf: glibtoolize is needed because this package uses Libtool

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

$ brew install libtool
Warning: libtool-2.4.6 already installed
```

**Comment by boothj5** [comment] 2016-05-23 20:54
All of the errors appear to point to `libtool` not being installed, but as you've shown it appears to be installed on your system, it could be something to do with homebrew paths...

Resorting to googling, the following may be relevant: http://apple.stackexchange.com/questions/108513/cant-exec-glibtoolize-no-such-file-or-directory

**Comment by tristan-k** [comment] 2016-05-24 13:16
I followed the instructions given in the stackexchange thread, but neither setting the PATH nor relink libtool worked. I'm not sure if this is realted to profanity, the brew profanity formula or brew itself.

```
$ brew unlink libtool && brew link libtool
Unlinking /usr/local/Cellar/libtool/2.4.6... 20 symlinks removed
Linking /usr/local/Cellar/libtool/2.4.6... 20 symlinks created
```

```
$ cat ~/.zshrc | grep PATH
export PATH="/usr/local/Cellar/libtool/2.4.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
```

**Comment by tristan-k** [comment] 2016-06-21 10:12
Still no success, anybody out there which is struggeling with that issue as well?

**Comment by geo242** [comment] 2016-07-15 01:50
I am having the same issue

**Comment by pasis** [comment] 2016-09-20 23:06
I've built Profanity on El Capitan. I had problem with libtool-2.4.6:
```
$ ./bootstrap.sh
/usr/local/bin/glibtoolize: line 406: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3601: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3845: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 861: /usr/local/Library/ENV/4.3/sed: No such file or directory
: putting auxiliary files in '.'.
: copying file './ltmain.sh'
/usr/local/bin/glibtoolize: line 3771: /usr/local/Library/ENV/4.3/sed: No such file or directory
configure.ac:87: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
```
This is because of broken path to sed. New version 2.4.6_1 fixes it: `brew upgrade libtool`. Next, I still had undefined AC_MSG_ERROR:
```
$ ./bootstrap.sh
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
glibtoolize: copying file 'build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
glibtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:87: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
```
I fixed it by installing `autoconf-archive`.

If you still have problem with absent glibtoolize, check if symlink installed properly (this is part of libtool):
```
$ ls -l /usr/local/bin/glibtoolize
lrwxr-xr-x  1 root  admin  41 Sep 21 01:41 /usr/local/bin/glibtoolize -> ../Cellar/libtool/2.4.6_1/bin/glibtoolize
```
If the symlink exists check your PATH.

**Comment by pasis** [comment] 2016-09-20 23:25
Seems, the problem is in PATH which doesn't contain /usr/local/bin

**Comment by jubalh** [comment] 2018-08-13 16:57
It sounds like this is not specifically an issue of profanity but of the tools and their versions used on OS X.

In the hope that @pasis instructions are helping in resolving this, I will close this issue. Feel free to reopen if needed.

**Closed by jubalh** 2018-08-13 16:57 UTC
Labels: query
