### ISSUE TITLE
Multiline paste

### ISSUE THREAD

**Issue by mmalisz** [boothj5/profanity#694] opened 2015-12-14 12:02 UTC
Profanity handles long text pasting quite poorly, it looks like it 'reproduces' every single character from the string (I can literally see the text being produced), plus pasting multiline text results in sending each line as new message.

**Comment by boothj5** [comment] 2015-12-14 21:53
Closing as this is a duplicate of #156 

This issue has been around for a long time, but I haven't started work on it yet.  It's also been requested a number of times so I'll try to look at it soon.

**Closed by boothj5** 2015-12-14 21:53 UTC

**Comment by mmalisz** [comment] 2015-12-15 07:16
Thanks, couldn't find it (read as being lazy ;-)), but thanks for the reply.
